### ISSUE TITLE
Match color of graph functions to describe output

### ISSUE THREAD

**Issue by maurelian** [GNSPS/soli#2]
It would be really helpful if functions in `graph` were colored by visibility, and if the coloring matched the `describe` color scheme. 

![image](https://user-images.githubusercontent.com/23033765/39494417-52daf096-4d64-11e8-911a-bab44afa67b5.png)

That would make it easy to see the entry points, and the describe command would serve as a legend.

**Comment by GNSPS** [comment]
Done
